# Docker image
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'terraform-azurerm-mariadb:$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'

- script: docker run --rm $(imageName) bash -c "./test.sh validate"
  displayName: 'validate'